//
// Created by Fryderyk Niedzwiecki on 14/01/2026.
//

#include "Game.h"
#include "../content/tribes/Tribe.h"
#include "../content/tech/TechDB.h"

#include "../systems/TurnSystem.h"
#include "../systems/MovementSystem.h"
#include "../systems/CombatSystem.h"
#include "../systems/InteractionSystem.h"
#include "../systems/VisionSystem.h"
#include "../systems/BuildingSystem.h"
#include "../systems/TechSystem.h"
#include "../systems/PlayerSystem.h"
#include "../systems/UnitSpawnSystem.h"
#include "../systems/TileActionSystem.h"
#include "../systems/GameDataSystem.h"
#include <random>

#include "../systems/ScoreSystem.h"
#include "../systems/UnitSystem.h"
#include "../systems/CitySystem.h"

#include "../systems/UnitUpgradeSystem.h"
#include "../systems/CityRewardSystem.h"
#include "../content/skills/UnitSkill.h"

#include <algorithm>

#include "../world/Tile.h"
#include "terrain/SettlementId.h"

namespace {
    static bool canCurrentPlayerAct(const Game& game, PlayerId pid) {
        return !game.isGameOver() && game.isPlayersTurn(pid) && !game.hasPendingCityUpgrade(pid);
    }

    static bool canControlUnit(const Game& game, PlayerId pid, UnitId unitId, bool requireActionSlot) {
        if (!UnitSystem::unitExists(game, unitId)) return false;
        if (UnitSystem::getOwnerId(game, unitId) != pid) return false;
        if (requireActionSlot) return canCurrentPlayerAct(game, pid);
        return game.isPlayersTurn(pid);
    }

}

// Game.cpp
City* Game::getCity(CityId id) {
    if (id == kNoCity || id >= cities.size()) return nullptr;
    return &cities[id];
}

const City* Game::getCity(CityId id) const {
    if (id == kNoCity || id >= cities.size()) return nullptr;
    return &cities[id];
}

void Game::newGame(const NewGameConfig& cfg) {
    // Load static game data (unit templates) before any units are spawned.
    if (!GameDataSystem::isUnitsLoaded()) {
        GameDataSystem::loadUnits("data/Units.json");
    }

    // 1) aktywne plemiona na mapie
    map.setActiveTribes(cfg.tribes);

    // 2) generacja mapy
    // Single source of truth for determinism.
    if (cfg.seed == 0) {
        std::random_device rd;
        worldSeed = (static_cast<uint32_t>(rd()) << 16) ^ static_cast<uint32_t>(rd());
        if (worldSeed == 0) worldSeed = 1u;
    } else {
        worldSeed = cfg.seed;
    }

    MapGenerator::Params p;
    p.mapSize = cfg.mapSize;
    p.initialLand = cfg.initialLand;
    p.smoothing = cfg.smoothing;
    p.relief = cfg.relief;
    p.seed = worldSeed;

    MapGenerator::generate(map, p);

    // Capitals generated by MapGenerator (same order as cfg.tribes / player indices)
    const auto& capitals = MapGenerator::getLastCapitals();

    cities.clear();
    cities.resize(cfg.tribes.size());

    for (size_t i = 0; i < cfg.tribes.size(); ++i) {
        const CityId cid = static_cast<CityId>(i);

        // Default city setup for all tribes
        (void)CitySystem::setCityId(*this, cid, cid);
        (void)CitySystem::setCityOwner(*this, cid, static_cast<uint8_t>(i));
        (void)CitySystem::setCityLevel(*this, cid, 1);
        (void)CitySystem::setCityPopulation(*this, cid, 0);
        (void)CitySystem::setCityStarsPerRound(*this, cid, 20);
        (void)CitySystem::setCityName(*this, cid, std::string("City ") + std::to_string(i));

        // IMPORTANT: store the city position (used by movement/connection systems).
        if (capitals.size() == cfg.tribes.size()) {
            (void)CitySystem::setCityPos(*this, cid, capitals[i]);
        }

        // Capitals generated by MapGenerator: each starting city is a capital
        (void)CitySystem::setCityCapital(*this, cid, true);

        // Special tribe rule: Luxidoor starts with a strong capital
        if (cfg.tribes[i] == TribeType::Luxidoor) {
            (void)CitySystem::setCityLevel(*this, cid, 3);
            (void)CitySystem::setCityStarsPerRound(*this, cid, 4);
            (void)CitySystem::setCityPopulation(*this, cid, 0);
        }
    }

    // 3) tworzymy graczy
    players.clear();
    players.reserve(cfg.tribes.size());

    for (size_t i = 0; i < cfg.tribes.size(); ++i) {
        PlayerId pid = static_cast<PlayerId>(i);

        // Startowe gwiazdki bierzemy z definicji plemienia (wiki defaults)
        const Tribe tribe = Tribe::makeDefault(cfg.tribes[i]);
        const int startStars = static_cast<int>(tribe.getStartStars());

        // capitalId is stable and matches MapGenerator (we use player index as capital/city id)
        const int capitalId = static_cast<int>(i);
        players.emplace_back(pid, cfg.tribes[i], startStars, capitalId);

        // Grant starting technology (new TechId-based tech system)
        const TechId startTech = tribe.getStartTech();
        if (startTech != TechId::Count) {
            PlayerSystem::addTech(*this, pid, startTech);
        }
    }

    // 3b) Initialize capitals (tile settlement + territory) via CitySystem.
    // Must happen after players are created, because initCapital also ensures player city list + capital id.
    if (capitals.size() == cfg.tribes.size()) {
        for (size_t i = 0; i < cfg.tribes.size(); ++i) {
            (void)CitySystem::initCapital(*this, static_cast<PlayerId>(i), static_cast<CityId>(i), capitals[i]);
        }
    }

    // 4) jednostki startowe
    units.clear();

    // 4b) spawn starting units on capitals (tribe default start unit)
    if (capitals.size() == cfg.tribes.size()) {
        for (size_t i = 0; i < players.size(); ++i) {
            const Pos cap = capitals[i];
            if (!map.inBounds(cap) || map.unitOn(cap) != Map::kNoUnit) continue;

            const Tribe tribe = Tribe::makeDefault(cfg.tribes[i]);
            const UnitType startType = tribe.getStartUnit().getType();

            const UnitId uid = spawnUnit(startType, static_cast<PlayerId>(i), cap, true);
            if (uid != kNoUnit) {
                (void)CitySystem::addUnitToCity(*this, uid, static_cast<CityId>(i));
            }
        }
    }

    // 4c) initial fog-of-war
    if (capitals.size() == players.size()) {
        for (size_t i = 0; i < players.size(); ++i) {
            VisionSystem::revealArea(*this, static_cast<PlayerId>(i), capitals[i], 2, RevealSource::Initial);
        }
    }

    for (size_t i = 0; i < players.size(); ++i) {
        VisionSystem::revealForPlayerFromUnits(*this, static_cast<PlayerId>(i));
    }

    currentPlayer = 0;
    turnNumber = 0;
    winner = kNoPlayer;

    // 5) start tury gracza 0
    TurnSystem::startTurn(*this);
    updateWinnerByCapitals();
}

bool Game::buyTech(PlayerId pid, TechId tech) {
    if (!isPlayersTurn(pid)) return false;
    if (hasPendingCityUpgrade(pid)) return false;
    return TechSystem::buyTech(*this, pid, tech);
}

bool Game::canBuyTech(PlayerId pid, TechId tech) const {
    if (!isPlayersTurn(pid)) return false;
    if (hasPendingCityUpgrade(pid)) return false;
    return TechSystem::canBuyTech(*this, pid, tech);
}

bool Game::endTurn(PlayerId pid) {
    if (isGameOver()) return false;
    if (!isPlayersTurn(pid)) return false;
    if (hasPendingCityUpgrade(pid)) return false;

    TurnSystem::endTurn(*this);

    currentPlayer = static_cast<PlayerId>((currentPlayer + 1) % players.size());
    if (currentPlayer == 0) {
        turnNumber++;
    }

    TurnSystem::startTurn(*this);
    return true;
}

Unit* Game::getUnit(UnitId id) {
    if (id == kNoUnit) return nullptr;
    if (id >= units.size()) return nullptr;
    return &units[id];
}

const Unit* Game::getUnit(UnitId id) const {
    if (id == kNoUnit) return nullptr;
    if (id >= units.size()) return nullptr;
    return &units[id];
}

// Spawns a unit on the map. If `canActImmediately` is false, the unit cannot move/attack until next turn.
UnitId Game::spawnUnit(UnitType type, PlayerId owner, Pos pos, bool canActImmediately) {
    if (!canActImmediately) {
        if (!isPlayersTurn(owner)) return kNoUnit;
        if (owner == kNoPlayer) return kNoUnit;
        if (!PlayerSystem::playerExists(*this, owner)) return kNoUnit;
    }

    return UnitSpawnSystem::spawnUnit(*this, map, type, owner, pos, canActImmediately);
}

bool Game::moveUnit(PlayerId pid, UnitId unitId, Pos to) {
    if (!canControlUnit(*this, pid, unitId, true)) return false;
    return MovementSystem::move(*this, unitId, to);
}

bool Game::canMoveUnit(PlayerId pid, UnitId unitId, Pos to) const {
    if (!canControlUnit(*this, pid, unitId, true)) return false;
    const std::vector<Pos> r = MovementSystem::reachable(*this, unitId);
    return std::find(r.begin(), r.end(), to) != r.end();
}

bool Game::handleRuin(PlayerId pid, UnitId unitId, Pos pos) {
    if (!canHandleRuin(pid, unitId, pos)) return false;

    InteractionSystem::handleRuin(*this, unitId, pos);
    return true;
}

bool Game::canHandleRuin(PlayerId pid, UnitId unitId, Pos pos) const {
    if (!canControlUnit(*this, pid, unitId, true)) return false;
    if (!map.inBounds(pos)) return false;
    if (UnitSystem::getPos(*this, unitId) != pos) return false;
    if (UnitSystem::movedThisTurn(*this, unitId) || UnitSystem::attackedThisTurn(*this, unitId)) return false;

    const Tile& t = map.at(pos);
    return t.getSettlementType() == SettlementTypeEnum::Ruin;
}

int Game::getPlayerScore(PlayerId pid) const {
    return ScoreSystem::getScore(*this, pid);
}

bool Game::handleStarfish(PlayerId pid, UnitId unitId, Pos pos) {
    if (!canHandleStarfish(pid, unitId, pos)) return false;

    InteractionSystem::handleStarfish(*this, unitId, pos);
    return true;
}

bool Game::canHandleStarfish(PlayerId pid, UnitId unitId, Pos pos) const {
    if (!canControlUnit(*this, pid, unitId, true)) return false;
    if (!map.inBounds(pos)) return false;
    if (UnitSystem::getPos(*this, unitId) != pos) return false;
    if (UnitSystem::movedThisTurn(*this, unitId) || UnitSystem::attackedThisTurn(*this, unitId)) return false;

    const Tile& t = map.at(pos);
    return t.getSettlementType() == SettlementTypeEnum::Starfish;
}

bool Game::handleCityCapture(PlayerId pid, UnitId unitId, Pos pos) {
    if (!canHandleCityCapture(pid, unitId, pos)) return false;
    if (!CitySystem::captureCityAt(*this, pid, pos)) return false;
    updateWinnerByCapitals();
    UnitSystem::setMovedThisTurn(*this, unitId, true);
    UnitSystem::setAttackedThisTurn(*this, unitId, true);
    return true;
}

bool Game::canHandleCityCapture(PlayerId pid, UnitId unitId, Pos pos) const {
    if (!canControlUnit(*this, pid, unitId, true)) return false;
    if (!map.inBounds(pos)) return false;
    if (UnitSystem::getPos(*this, unitId) != pos) return false;
    if (UnitSystem::movedThisTurn(*this, unitId) || UnitSystem::attackedThisTurn(*this, unitId)) return false;
    return CitySystem::canCaptureCityAt(*this, pid, pos);
}

std::vector<Pos> Game::reachable(PlayerId pid, UnitId unitId) const {
    if (!canControlUnit(*this, pid, unitId, false)) return {};
    return MovementSystem::reachable(*this, unitId);
}

bool Game::attack(PlayerId pid, UnitId attackerId, Pos target) {
    if (!canControlUnit(*this, pid, attackerId, true)) return false;
    return CombatSystem::attack(*this, attackerId, target);
}

bool Game::canAttack(PlayerId pid, UnitId attackerId, Pos target) const {
    if (!canControlUnit(*this, pid, attackerId, true)) return false;
    const std::vector<Pos> a = CombatSystem::attackable(*this, attackerId);
    return std::find(a.begin(), a.end(), target) != a.end();
}


bool Game::heal(PlayerId pid, UnitId healerId) {
    if (!canControlUnit(*this, pid, healerId, true)) return false;
    return CombatSystem::heal(*this, healerId);
}

bool Game::canHeal(PlayerId pid, UnitId healerId) const {
    if (!canControlUnit(*this, pid, healerId, true)) return false;
    if (!UnitSystem::hasSkill(*this, healerId, UnitSkill::Heal)) return false;
    if (UnitSystem::attackedThisTurn(*this, healerId)) return false;
    if (UnitSystem::movedThisTurn(*this, healerId) && !UnitSystem::hasSkill(*this, healerId, UnitSkill::Dash)) return false;

    const Pos center = UnitSystem::getPos(*this, healerId);
    if (!map.inBounds(center)) return false;

    for (int dy = -1; dy <= 1; ++dy) {
        for (int dx = -1; dx <= 1; ++dx) {
            if (dx == 0 && dy == 0) continue;

            const Pos p{center.x + dx, center.y + dy};
            if (!map.inBounds(p)) continue;

            const UnitId uid = map.unitOn(p);
            if (uid == Map::kNoUnit) continue;
            if (!UnitSystem::unitExists(*this, uid)) continue;
            if (UnitSystem::getOwnerId(*this, uid) != pid) continue;
            if (UnitSystem::getHealth(*this, uid) <= 0) continue;
            if (UnitSystem::getHealth(*this, uid) >= UnitSystem::getMaxHealth(*this, uid)) continue;
            return true;
        }
    }
    return false;
}

std::vector<Pos> Game::attackable(PlayerId pid, UnitId attackerId) const {
    if (!canControlUnit(*this, pid, attackerId, false)) return {};
    return CombatSystem::attackable(*this, attackerId);
}

bool Game::buildBuilding(PlayerId builder, Pos pos, BuildingTypeEnum type) {
    if (!isPlayersTurn(builder)) return false;
    if (hasPendingCityUpgrade(builder)) return false;
    if (!map.inBounds(pos)) return false;

    const Tile& t = map.at(pos);
    const CityId cid = t.getTerritoryCityId();
    if (cid == kNoCity) return false;
    if (!CitySystem::cityExists(*this, cid)) return false;
    if (static_cast<PlayerId>(CitySystem::getCityOwner(*this, cid)) != builder) return false;

    return BuildingSystem::build(*this, builder, pos, type);
}

bool Game::canBuildBuilding(PlayerId builder, Pos pos, BuildingTypeEnum type) const {
    if (!isPlayersTurn(builder)) return false;
    if (hasPendingCityUpgrade(builder)) return false;
    if (!map.inBounds(pos)) return false;

    const Tile& t = map.at(pos);
    const CityId cid = t.getTerritoryCityId();
    if (cid == kNoCity) return false;
    if (!CitySystem::cityExists(*this, cid)) return false;
    if (static_cast<PlayerId>(CitySystem::getCityOwner(*this, cid)) != builder) return false;

    return BuildingSystem::canBuild(*this, builder, pos, type);
}

// ---- Tile actions wrappers ----

bool Game::hunt(PlayerId pid, Pos pos) {
    if (!isPlayersTurn(pid)) return false;
    if (hasPendingCityUpgrade(pid)) return false;
    if (!map.inBounds(pos)) return false;
    return TileActionSystem::hunt(*this, pid, pos);
}

bool Game::canHunt(PlayerId pid, Pos pos) const {
    if (!canCurrentPlayerAct(*this, pid)) return false;
    if (!map.inBounds(pos)) return false;
    return TileActionSystem::canHunt(*this, pid, pos);
}

bool Game::organization(PlayerId pid, Pos pos) {
    if (!isPlayersTurn(pid)) return false;
    if (hasPendingCityUpgrade(pid)) return false;
    if (!map.inBounds(pos)) return false;
    return TileActionSystem::organization(*this, pid, pos);
}

bool Game::canOrganization(PlayerId pid, Pos pos) const {
    if (!canCurrentPlayerAct(*this, pid)) return false;
    if (!map.inBounds(pos)) return false;
    return TileActionSystem::canOrganization(*this, pid, pos);
}

bool Game::fishing(PlayerId pid, Pos pos) {
    if (!isPlayersTurn(pid)) return false;
    if (hasPendingCityUpgrade(pid)) return false;
    if (!map.inBounds(pos)) return false;
    return TileActionSystem::fishing(*this, pid, pos);
}

bool Game::canFishing(PlayerId pid, Pos pos) const {
    if (!canCurrentPlayerAct(*this, pid)) return false;
    if (!map.inBounds(pos)) return false;
    return TileActionSystem::canFishing(*this, pid, pos);
}

bool Game::clearForest(PlayerId pid, Pos pos) {
    if (!isPlayersTurn(pid)) return false;
    if (hasPendingCityUpgrade(pid)) return false;
    if (!map.inBounds(pos)) return false;
    return TileActionSystem::clearForest(*this, pid, pos);
}

bool Game::canClearForest(PlayerId pid, Pos pos) const {
    if (!canCurrentPlayerAct(*this, pid)) return false;
    if (!map.inBounds(pos)) return false;
    return TileActionSystem::canClearForest(*this, pid, pos);
}

bool Game::burnForest(PlayerId pid, Pos pos) {
    if (!isPlayersTurn(pid)) return false;
    if (hasPendingCityUpgrade(pid)) return false;
    if (!map.inBounds(pos)) return false;
    return TileActionSystem::burnForest(*this, pid, pos);
}

bool Game::canBurnForest(PlayerId pid, Pos pos) const {
    if (!canCurrentPlayerAct(*this, pid)) return false;
    if (!map.inBounds(pos)) return false;
    return TileActionSystem::canBurnForest(*this, pid, pos);
}

bool Game::growForest(PlayerId pid, Pos pos) {
    if (!isPlayersTurn(pid)) return false;
    if (hasPendingCityUpgrade(pid)) return false;
    if (!map.inBounds(pos)) return false;
    return TileActionSystem::growForest(*this, pid, pos);
}

bool Game::canGrowForest(PlayerId pid, Pos pos) const {
    if (!canCurrentPlayerAct(*this, pid)) return false;
    if (!map.inBounds(pos)) return false;
    return TileActionSystem::canGrowForest(*this, pid, pos);
}

bool Game::destroyTile(PlayerId pid, Pos pos) {
    if (!isPlayersTurn(pid)) return false;
    if (hasPendingCityUpgrade(pid)) return false;
    if (!map.inBounds(pos)) return false;
    return TileActionSystem::destroy(*this, pid, pos);
}

bool Game::canDestroyTile(PlayerId pid, Pos pos) const {
    if (!canCurrentPlayerAct(*this, pid)) return false;
    if (!map.inBounds(pos)) return false;
    return TileActionSystem::canDestroy(*this, pid, pos);
}

bool Game::buildRoad(PlayerId pid, Pos pos) {
    if (!isPlayersTurn(pid)) return false;
    if (hasPendingCityUpgrade(pid)) return false;
    if (!map.inBounds(pos)) return false;
    return TileActionSystem::buildRoad(*this, pid, pos);
}

bool Game::canBuildRoad(PlayerId pid, Pos pos) const {
    if (!canCurrentPlayerAct(*this, pid)) return false;
    if (!map.inBounds(pos)) return false;
    return TileActionSystem::canBuildRoad(*this, pid, pos);
}

std::vector<BuildingTypeEnum> Game::getPlayerEarnedMonuments(PlayerId pid) const {
    if (!PlayerSystem::playerExists(*this, pid)) return {};
    return PlayerSystem::getEarnedMonuments(*this, pid);
}

std::vector<BuildingTypeEnum> Game::getPlayerPlacedMonuments(PlayerId pid) const {
    if (!PlayerSystem::playerExists(*this, pid)) return {};
    return PlayerSystem::getPlacedMonuments(*this, pid);
}

std::vector<BuildingTypeEnum> Game::getPlayerOwnedMonuments(PlayerId pid) const {
    if (!PlayerSystem::playerExists(*this, pid)) return {};
    return PlayerSystem::getOwnedMonuments(*this, pid);
}

bool Game::explorer(PlayerId pid, Pos start) {
    if (!canCurrentPlayerAct(*this, pid)) return false;
    if (!map.inBounds(start)) return false;
    VisionSystem::doExplorer(*this, pid, start);
    return true;
}

bool Game::canExplorer(PlayerId pid, Pos start) const {
    if (!isPlayersTurn(pid)) return false;
    if (hasPendingCityUpgrade(pid)) return false;
    return map.inBounds(start);
}

bool Game::buildBridge(PlayerId pid, Pos pos) {
    if (!isPlayersTurn(pid)) return false;
    if (hasPendingCityUpgrade(pid)) return false;
    if (!map.inBounds(pos)) return false;
    return TileActionSystem::buildBridge(*this, pid, pos);
}

bool Game::canBuildBridge(PlayerId pid, Pos pos) const {
    if (!canCurrentPlayerAct(*this, pid)) return false;
    if (!map.inBounds(pos)) return false;
    return TileActionSystem::canBuildBridge(*this, pid, pos);
}

// ---- City actions ----

bool Game::foundCityFromVillage(PlayerId pid, Pos pos) {
    if (!isPlayersTurn(pid)) return false;
    if (hasPendingCityUpgrade(pid)) return false;
    return CitySystem::foundCityFromVillage(*this, pid, pos);
}

bool Game::canFoundCityFromVillage(PlayerId pid, Pos pos) const {
    if (!canCurrentPlayerAct(*this, pid)) return false;
    return CitySystem::canFoundCityFromVillage(*this, pid, pos);
}

bool Game::canUpgradeCity(PlayerId pid, CityId cityId) const {
    if (!isPlayersTurn(pid)) return false;
    if (!CitySystem::cityExists(*this, cityId)) return false;

    const PlayerId owner = static_cast<PlayerId>(CitySystem::getCityOwner(*this, cityId));
    if (owner != pid) return false;

    const PendingCityUpgrade* p = peekPendingCityUpgrade(pid);
    return p && p->cityId == cityId;
}

CityUpgradeOptions Game::getCityUpgradeOptions(PlayerId pid, CityId cityId) const {
    CityUpgradeOptions out{};

    if (!isPlayersTurn(pid)) return out;
    if (!CitySystem::cityExists(*this, cityId)) return out;

    const PlayerId owner = static_cast<PlayerId>(CitySystem::getCityOwner(*this, cityId));
    if (owner != pid) return out;

    const PendingCityUpgrade* p = peekPendingCityUpgrade(pid);
    if (!p || p->cityId != cityId) return out;
    return p->opts;
}

bool Game::upgradeCity(PlayerId pid, CityId cityId, CityUpgradeChoice choice) {
    if (!isPlayersTurn(pid)) return false;
    if (!CitySystem::cityExists(*this, cityId)) return false;

    const PlayerId owner = static_cast<PlayerId>(CitySystem::getCityOwner(*this, cityId));
    if (owner != pid) return false;

    if (pendingCityUpgrades.empty()) return false;
    const PendingCityUpgrade& front = pendingCityUpgrades.front();
    if (front.pid != pid) return false;
    if (front.cityId != cityId) return false;

    if (choice != front.opts.a && choice != front.opts.b) return false;

    if (!CityRewardSystem::tryUpgrade(*this, cityId, choice)) return false;

    pendingCityUpgrades.pop_front();
    return true;
}


bool Game::captureCityAt(PlayerId pid, Pos pos) {
    if (!isPlayersTurn(pid)) return false;
    if (hasPendingCityUpgrade(pid)) return false;
    if (!CitySystem::captureCityAt(*this, pid, pos)) return false;
    updateWinnerByCapitals();
    return true;
}

bool Game::canCaptureCityAt(PlayerId pid, Pos pos) const {
    if (!canCurrentPlayerAct(*this, pid)) return false;
    return CitySystem::canCaptureCityAt(*this, pid, pos);
}

// ---- Raft upgrades (pid-first + legacy delegate) ----

bool Game::canUpgradeRaftToScout(PlayerId pid, UnitId unitId) const {
    if (!canControlUnit(*this, pid, unitId, false)) return false;
    return UnitUpgradeSystem::canUpgradeRaftToScout(*this, unitId);
}


bool Game::canUpgradeRaftToRammer(PlayerId pid, UnitId unitId) const {
    if (!canControlUnit(*this, pid, unitId, false)) return false;
    return UnitUpgradeSystem::canUpgradeRaftToRammer(*this, unitId);
}


bool Game::canUpgradeRaftToBomber(PlayerId pid, UnitId unitId) const {
    if (!canControlUnit(*this, pid, unitId, false)) return false;
    return UnitUpgradeSystem::canUpgradeRaftToBomber(*this, unitId);
}


bool Game::upgradeRaftToScout(PlayerId pid, UnitId unitId) {
    if (!canControlUnit(*this, pid, unitId, true)) return false;
    return UnitUpgradeSystem::upgradeRaftToScout(*this, unitId);
}


bool Game::upgradeRaftToRammer(PlayerId pid, UnitId unitId) {
    if (!canControlUnit(*this, pid, unitId, true)) return false;
    return UnitUpgradeSystem::upgradeRaftToRammer(*this, unitId);
}


bool Game::upgradeRaftToBomber(PlayerId pid, UnitId unitId) {
    if (!canControlUnit(*this, pid, unitId, true)) return false;
    return UnitUpgradeSystem::upgradeRaftToBomber(*this, unitId);
}


// ---- Veteran (pid-first + legacy delegate) ----

bool Game::canUnitBecomeVeteran(PlayerId pid, UnitId unitId) const {
    if (!canControlUnit(*this, pid, unitId, false)) return false;
    return UnitUpgradeSystem::canUnitBecomeVeteran(*this, unitId);
}


bool Game::becomeVeteran(PlayerId pid, UnitId unitId) {
    if (!canControlUnit(*this, pid, unitId, true)) return false;
    return UnitUpgradeSystem::becomeVeteran(*this, unitId);
}


uint16_t Game::getLighthouseDiscoveredByMask(uint8_t lighthouseIdx) const {
    return (lighthouseIdx < lighthouseDiscoveredBy.size()) ? lighthouseDiscoveredBy[lighthouseIdx] : 0;
}

bool Game::hasPlayerDiscoveredLighthouse(uint8_t lighthouseIdx, PlayerId pid) const {
    if (lighthouseIdx >= lighthouseDiscoveredBy.size()) return false;
    if (pid == kNoPlayer) return false;
    const uint16_t bit = static_cast<uint16_t>(1u << static_cast<uint16_t>(pid));
    return (lighthouseDiscoveredBy[lighthouseIdx] & bit) != 0;
}

bool Game::markLighthouseDiscovered(uint8_t lighthouseIdx, PlayerId pid) {
    if (lighthouseIdx >= lighthouseDiscoveredBy.size()) return false;
    if (pid == kNoPlayer) return false;

    const uint16_t bit = static_cast<uint16_t>(1u << static_cast<uint16_t>(pid));
    uint16_t& mask = lighthouseDiscoveredBy[lighthouseIdx];

    if (mask & bit) return false; // już odkrył wcześniej
    mask |= bit;
    return true;
}

bool Game::hasPendingCityUpgrade(PlayerId pid) const {
    for (const auto& p : pendingCityUpgrades) {
        if (p.pid == pid) return true;
    }
    return false;
}

const Game::PendingCityUpgrade* Game::peekPendingCityUpgrade(PlayerId pid) const {
    for (const auto& p : pendingCityUpgrades) {
        if (p.pid == pid) return &p;
    }
    return nullptr;
}

bool Game::enqueuePendingCityUpgrade(PlayerId pid, CityId cityId) {
    // Prevent duplicates for the same (pid, cityId)
    for (const auto& p : pendingCityUpgrades) {
        if (p.pid == pid && p.cityId == cityId) return false;
    }

    // Level-up is performed in CitySystem/City; we only enqueue the reward choice.
    pendingCityUpgrades.push_back(PendingCityUpgrade{
        pid,
        cityId,
        CityRewardSystem::getUpgradeOptions(*this, cityId),
        turnNumber
    });
    return true;
}

bool Game::resolvePendingCityUpgrade(PlayerId pid, CityUpgradeChoice choice) {
    if (pendingCityUpgrades.empty()) return false;

    const PendingCityUpgrade& front = pendingCityUpgrades.front();
    if (front.pid != pid) return false;

    if (choice != front.opts.a && choice != front.opts.b) return false;

    if (!CityRewardSystem::tryUpgrade(*this, front.cityId, choice)) return false;

    pendingCityUpgrades.pop_front();
    return true;
}

bool Game::hasPlayerSeenCorner(PlayerId pid, MapCorner corner) const {
    if (pid == kNoPlayer) return false;

    const int max = map.getWidth() - 1;

    Pos p{0, 0};
    switch (corner) {
        case MapCorner::TopLeft:     p = Pos{0, 0}; break;
        case MapCorner::BottomLeft:  p = Pos{0, max}; break;
        case MapCorner::TopRight:    p = Pos{max, 0}; break;
        case MapCorner::BottomRight: p = Pos{max, max}; break;
    }

    if (!map.inBounds(p)) return false;

    const Tile& t = map.at(p);
    const uint16_t mask = static_cast<uint16_t>(t.getVisibility());

    const uint32_t idx = static_cast<uint32_t>(pid);
    if (idx >= 16) return false;

    return (mask & (uint16_t(1) << idx)) != 0;
}

void Game::updateWinnerByCapitals() {
    PlayerId capitalOwner = kNoPlayer;
    int capitalsCount = 0;

    for (const City& c : cities) {
        if (!c.getIsCapital()) continue;
        ++capitalsCount;

        const PlayerId owner = static_cast<PlayerId>(c.getOwnerId());
        if (owner == kNoPlayer) {
            winner = kNoPlayer;
            return;
        }

        if (capitalOwner == kNoPlayer) {
            capitalOwner = owner;
        } else if (capitalOwner != owner) {
            winner = kNoPlayer;
            return;
        }
    }

    if (capitalsCount == 0) {
        winner = kNoPlayer;
        return;
    }

    winner = capitalOwner;
}
