//
// Created by Fryderyk Niedzwiecki on 07/02/2026.
//

#ifndef GAME_ENGINE_STARSSYSTEM_H
#define GAME_ENGINE_STARSSYSTEM_H

#include "Game.h"
#include "Core/Ids.h"

class StarsSystem {
public:
    // --- Total income calculation ---
    // Calculates how many stars a player should receive this turn (does NOT add them).
    static int calcIncomeForPlayer(const Game& game, PlayerId pid);

    // Applies income to the player (adds stars, handles siege/infiltration rules).
    static void applyIncomeForPlayer(Game& game, PlayerId pid);

    // --- Market income helpers ---
    // Calculates income generated by all Markets in a specific city.
    static int marketIncomeForCity(const Game& game, PlayerId pid, CityId cid);
};

#endif //GAME_ENGINE_STARSSYSTEM_H