//
// Created by Fryderyk Niedzwiecki on 14/01/2026.
//

#include "Game.h"
#include "tribes/Tribe.h"
#include "tech/TechDB.h"

// tu includujesz systemy (w .cpp, nie w .h)
#include "Systems/TurnSystem.h"
#include "Systems/MovementSystem.h"
#include "Systems/CombatSystem.h"
#include "Systems/InteractionSystem.h"
#include "Systems/VisionSystem.h"
#include "Systems/BuildingSystem.h"
#include "Systems/UnitSpawnSystem.h"
#include "Systems/TileActionSystem.h"
#include "Systems/UnitUpgradeSystem.h"
#include "units/UnitFactory.h"

#include <algorithm>
#include <iostream>

#include <array>

#include "World/Tile.h"
#include "terrain/SettlementTypeEnum.h"
#include "terrain/SettlementId.h"

// Remove unit from any city it is currently registered in, then add it to `newCityId`.
// This keeps City::units consistent when a unit captures/founds a city.
static void reassignUnitToCity(std::vector<City>& cities, UnitId uid, CityId newCityId) {
    if (uid == kNoUnit || newCityId == kNoCity) return;

    // Remove from any old city
    for (City& c : cities) {
        c.removeUnit(uid);
    }

    // Add to new city (if it exists)
    const size_t idx = static_cast<size_t>(newCityId);
    if (idx < cities.size()) {
        cities[idx].addUnit(uid);
    }
}

// Claim free (unassigned) territory in radius 1 around a city center.
// "Free" means: the tile is not already assigned to any city territory.
static void claimFreeTerritoryRadius1(Map& map, CityId cid, SettlementId citySid, Pos center) {
    if (cid == kNoCity) return;

    auto tryClaim = [&](Pos p) {
        if (!map.inBounds(p)) return;
        Tile& tt = map.at(p);

        // Do not override existing territory ownership.
        if (tt.getTerritoryCityId() != kNoCity) return;

        // Do not steal another city's center tile.
        if (tt.getSettlementType() == SettlementTypeEnum::City) {
            const SettlementId otherSid = tt.getSettlementId();
            if (otherSid != kNoSettlement && otherSid != citySid) return;
        }

        tt.setTerritoryCityId(cid);
    };

    // City tile itself
    tryClaim(center);

    // 8-neighborhood around the city (distance 1)
    static const std::array<Pos, 8> kNb = {
        Pos{ 1, 0}, Pos{-1, 0}, Pos{0, 1}, Pos{0,-1},
        Pos{ 1, 1}, Pos{ 1,-1}, Pos{-1, 1}, Pos{-1,-1}
    };
    for (const Pos d : kNb) {
        tryClaim(Pos{center.x + d.x, center.y + d.y});
    }
}

// Game.cpp
City* Game::getCity(CityId id) {
    if (id == kNoCity || id >= cities.size()) return nullptr;
    return &cities[id];
}

const City* Game::getCity(CityId id) const {
    if (id == kNoCity || id >= cities.size()) return nullptr;
    return &cities[id];
}

void Game::newGame(const NewGameConfig& cfg) {
    // 1) aktywne plemiona na mapie
    map.setActiveTribes(cfg.tribes);

    // 2) generacja mapy
    MapGenerator::Params p;
    p.mapSize = cfg.mapSize;
    p.initialLand = cfg.initialLand;
    p.smoothing = cfg.smoothing;
    p.relief = cfg.relief;
    p.seed = cfg.seed;

    MapGenerator::generate(map, p);

    // Capitals generated by MapGenerator (same order as cfg.tribes / player indices)
    const auto& capitals = MapGenerator::getLastCapitals();

    cities.clear();
    cities.resize(cfg.tribes.size());

    for (size_t i = 0; i < cfg.tribes.size(); ++i) {
        City& c = cities[i];

        // Default city setup for all tribes
        c.setCityId(static_cast<CityId>(i));
        c.setOwnerId(static_cast<uint8_t>(i));
        c.setLevel(1);
        c.setPopulation(0);
        c.setStarsPerRound(20);
        c.setName(std::string("City ") + std::to_string(i));

        // Capitals generated by MapGenerator: each starting city is a capital
        c.setCapital(true);

        // Special tribe rule: Luxidoor starts with a strong capital
        if (cfg.tribes[i] == TribeType::Luxidoor) {
            c.setLevel(3);
            c.setStarsPerRound(4);
            c.setPopulation(0); // reasonable population for level 3
        }
    }

    // 3) tworzymy graczy
    players.clear();
    players.reserve(cfg.tribes.size());

    for (size_t i = 0; i < cfg.tribes.size(); ++i) {
        PlayerId pid = static_cast<PlayerId>(i);

        // Startowe gwiazdki bierzemy z definicji plemienia (wiki defaults)
        const Tribe tribe = Tribe::makeDefault(cfg.tribes[i]);
        const int startStars = static_cast<int>(tribe.getStartStars());

        // capitalId is stable and matches MapGenerator (we use player index as capital/city id)
        const int capitalId = static_cast<int>(i);
        players.emplace_back(pid, cfg.tribes[i], startStars, capitalId);
        // Ensure player's city list contains the starting capital (needed for tech price scaling).
        players.back().addCity(static_cast<CityId>(capitalId));
        // Grant starting technology (new TechId-based tech system)
        const TechId startTech = tribe.getStartTech();
        if (startTech != TechId::Count) {
            players.back().addTech(startTech);
        }
    }

    // 4) jednostki startowe (na start np. warrior w stolicy)
    units.clear();
    // NIE nadpisuj kafelków mapy tutaj — MapGenerator już je wygenerował.

    // 4b) spawn starting units on capitals (simple default: Warrior on each capital)
    // 4b) spawn starting units on capitals (tribe default start unit)
    if (capitals.size() == cfg.tribes.size()) {
        for (size_t i = 0; i < players.size(); ++i) {
            const Pos cap = capitals[i];
            if (!map.inBounds(cap) || map.unitOn(cap) != Map::kNoUnit) continue;

            const Tribe tribe = Tribe::makeDefault(cfg.tribes[i]);
            const UnitType startType = tribe.getStartUnit().getType(); // Oumaji => Rider

            // Ensure the capital tile is linked to the capital City via SettlementId.
            // IMPORTANT: do NOT change tile tribe here (tile tribe = biome/terrain).
            {
                Tile& t = map.at(cap);
                const CityId cid = cities[i].getCityId();
                const SettlementId sid = static_cast<SettlementId>(cid);
                t.setSettlement(SettlementTypeEnum::City, sid);

                // Initialize territory for the starting capital so Map View can show ownership & highlight.
                claimFreeTerritoryRadius1(map, cid, sid, cap);
            }

            const UnitId uid = spawnUnit(startType, static_cast<PlayerId>(i), cap,true);
            if (uid != kNoUnit) {
                cities[i].addUnit(uid);
            }
        }
    }

    // 4c) initial fog-of-war: each player sees radius 2 around their capital.
    if (capitals.size() == players.size()) {
        for (size_t i = 0; i < players.size(); ++i) {
            VisionSystem::revealArea(*this, static_cast<PlayerId>(i), capitals[i], 2);
        }
    }

    // Also reveal from all units once (in case units have different vision rules).
    for (size_t i = 0; i < players.size(); ++i) {
        VisionSystem::revealForPlayerFromUnits(*this, static_cast<PlayerId>(i));
    }
    currentPlayer = 0;
    turnNumber = 0;

    // 5) start tury gracza 0
    TurnSystem::startTurn(*this);
}

bool Game::endTurn() {
    // kończ turę aktualnego gracza
    TurnSystem::endTurn(*this);

    // następny gracz
    currentPlayer = static_cast<PlayerId>((currentPlayer + 1) % players.size());
    if (currentPlayer == 0) {
        turnNumber++;
    }

    // rozpocznij turę nowego gracza
    TurnSystem::startTurn(*this);
    return true;
}

Unit* Game::getUnit(UnitId id) {
    if (id == kNoUnit) return nullptr;
    if (id >= units.size()) return nullptr;
    return &units[id];
}

const Unit* Game::getUnit(UnitId id) const {
    if (id == kNoUnit) return nullptr;
    if (id >= units.size()) return nullptr;
    return &units[id];
}

// Spawns a unit on the map. If `canActImmediately` is false, the unit cannot move/attack until next turn.
UnitId Game::spawnUnit(UnitType type, PlayerId owner, Pos pos, bool canActImmediately) {

    if (!canActImmediately) {
        if (!isPlayersTurn(owner)) return kNoUnit;

        if (owner == kNoPlayer) return kNoUnit;
        if (static_cast<size_t>(owner) >= players.size()) return kNoUnit;
    }

    return UnitSpawnSystem::spawnUnit(*this, map, type, owner, pos, canActImmediately);
}


bool Game::moveUnit(UnitId unitId, Pos to) {
    Unit* u = getUnit(unitId);
    if (!u) return false;

    // kolejka tur
    if (!isPlayersTurn(u->getOwnerId())) return false;

    bool ok = MovementSystem::move(*this, unitId, to);
    if (!ok) return false;

    // Fog-of-war: reveal newly seen area from this unit's new position.
    // VisionSystem::revealFromUnit(*this, unitId);

    // interakcje: ruin/starfish/village itd.
    InteractionSystem::onUnitEnteredTile(*this, unitId, to);
    return true;
}

std::vector<Pos> Game::reachable(UnitId unitId) const {
    const Unit* u = getUnit(unitId);
    if (!u) return {};

    // kolejka tur (tak jak przy ruchu)
    if (!isPlayersTurn(u->getOwnerId())) return {};

    return MovementSystem::reachable(*this, unitId);
}


bool Game::attack(UnitId attackerId, Pos target) {
    Unit* a = getUnit(attackerId);
    if (!a) return false;

    // kolejka tur
    if (!isPlayersTurn(a->getOwnerId())) return false;

    return CombatSystem::attack(*this, attackerId, target);
}

std::vector<Pos> Game::attackable(UnitId attackerId) const {
    const Unit* a = getUnit(attackerId);
    if (!a) return {};

    // kolejka tur (tak jak przy ataku)
    if (!isPlayersTurn(a->getOwnerId())) return {};

    return CombatSystem::attackable(*this, attackerId);
}

bool Game::buildBuilding(PlayerId builder, Pos pos, BuildingTypeEnum type) {
    // Must be the builder's turn.
    if (!isPlayersTurn(builder)) return false;

    // Must be within map bounds.
    if (!map.inBounds(pos)) return false;

    // Must belong to some city territory and that city must belong to the builder.
    const Tile& t = map.at(pos);
    const CityId cid = t.getTerritoryCityId();
    if (cid == kNoCity) return false;
    const City* c = getCity(cid);
    if (!c) return false;
    if (static_cast<PlayerId>(c->getOwnerId()) != builder) return false;

    // Delegate rules + star spending to the BuildingSystem.
    return BuildingSystem::build(*this, builder, pos, type);
}

// ---- Tile actions wrappers ----

bool Game::hunt(PlayerId pid, Pos pos) {
    if (!isPlayersTurn(pid)) return false;
    if (!map.inBounds(pos)) return false;
    return TileActionSystem::hunt(*this, pid, pos);
}

bool Game::organization(PlayerId pid, Pos pos) {
    if (!isPlayersTurn(pid)) return false;
    if (!map.inBounds(pos)) return false;
    return TileActionSystem::oraganization(*this, pid, pos);
}


bool Game::fishing(PlayerId pid, Pos pos) {
    if (!isPlayersTurn(pid)) return false;
    if (!map.inBounds(pos)) return false;
    return TileActionSystem::fishing(*this, pid, pos);
}

bool Game::clearForest(PlayerId pid, Pos pos) {
    if (!isPlayersTurn(pid)) return false;
    if (!map.inBounds(pos)) return false;
    return TileActionSystem::clearForest(*this, pid, pos);
}

bool Game::burnForest(PlayerId pid, Pos pos) {
    if (!isPlayersTurn(pid)) return false;
    if (!map.inBounds(pos)) return false;
    return TileActionSystem::burnForest(*this, pid, pos);
}

bool Game::growForest(PlayerId pid, Pos pos) {
    if (!isPlayersTurn(pid)) return false;
    if (!map.inBounds(pos)) return false;
    return TileActionSystem::growForest(*this, pid, pos);
}

bool Game::destroyTile(PlayerId pid, Pos pos) {
    if (!isPlayersTurn(pid)) return false;
    if (!map.inBounds(pos)) return false;
    return TileActionSystem::destroy(*this, pid, pos);
}

bool Game::buildRoad(PlayerId pid, Pos pos) {
    if (!isPlayersTurn(pid)) return false;
    if (!map.inBounds(pos)) return false;
    return TileActionSystem::buildRoad(*this, pid, pos);
}

bool Game::explorer(PlayerId pid, Pos start) {
    std::cout << "[explorer] pid=" << int(pid) << " start=(" << start.x << "," << start.y << ")\n";
    if (!isPlayersTurn(pid)) return false;
    if (!map.inBounds(start)) return false;
    VisionSystem::doExplorer(*this, pid, start);
    return true;
}

bool Game::buildBridge(PlayerId pid, Pos pos) {
    if (!isPlayersTurn(pid)) return false;
    if (!map.inBounds(pos)) return false;
    return TileActionSystem::buildBridge(*this, pid, pos);
}


bool Game::foundCityFromVillage(PlayerId owner, Pos pos) {
    if (!map.inBounds(pos)) return false;

    Tile& tile = map.at(pos);

    // Accept both cases:
    // - still a Village (caller didn't flip yet)
    // - already flipped to City by Interaction
    const SettlementTypeEnum st = tile.getSettlementType();
    if (st != SettlementTypeEnum::Village && st != SettlementTypeEnum::City) return false;

    // Resolve / allocate a settlement id.
    SettlementId sid = tile.getSettlementId();
    CityId cid = kNoCity;

    if (sid != kNoSettlement) {
        cid = static_cast<CityId>(sid);
        if (cid < 0) return false;
        if (static_cast<size_t>(cid) >= cities.size()) {
            cities.resize(static_cast<size_t>(cid) + 1);
        }
    } else {
        cid = static_cast<CityId>(cities.size());
        cities.resize(cities.size() + 1);
        sid = static_cast<SettlementId>(cid);
    }

    City& c = cities[static_cast<size_t>(cid)];

    // Initialize / overwrite city data
    c.setCityId(cid);
    c.setOwnerId(static_cast<uint8_t>(owner));
    c.setLevel(1);
    c.setPopulation(0);
    c.setStarsPerRound(1);
    c.setCapital(false);
    if (c.getName().empty()) {
        c.setName(std::string("City ") + std::to_string(static_cast<int>(cid)));
    }

    // Ensure tile points to this city id.
    tile.setSettlement(SettlementTypeEnum::City, sid);

    claimFreeTerritoryRadius1(map, cid, sid, pos);

    // Set ownership visuals/marker on the tile.
    // tile.setTribe(getPlayer(owner).getTribeType());

    // Register the city in the owner's city list (needed for tech price scaling).
    {
        Player& pl = getPlayer(owner);
        const auto& cs = pl.getCities();
        if (std::find(cs.begin(), cs.end(), cid) == cs.end()) {
            pl.addCity(cid);
        }
        if (pl.getCapitalId() == kNoCity) {
            pl.setCapitalId(cid);
        }
    }

    // If a unit is standing on the tile (it is the founder), reassign it to this new city.
    {
        const UnitId uOn = map.unitOn(pos);
        if (uOn != Map::kNoUnit) {
            reassignUnitToCity(cities, uOn, cid);
        }
    }

    return true;
}

City* Game::getCityBySettlementId(SettlementId sid) {
    if (sid == kNoSettlement) return nullptr;
    return getCity(static_cast<CityId>(sid));
}

const City* Game::getCityBySettlementId(SettlementId sid) const {
    if (sid == kNoSettlement) return nullptr;
    return getCity(static_cast<CityId>(sid));
}

bool Game::captureCityAt(PlayerId newOwner, Pos pos) {
    if (!map.inBounds(pos)) return false;

    Tile& tile = map.at(pos);
    if (tile.getSettlementType() != SettlementTypeEnum::City) return false;

    City* c = getCityBySettlementId(tile.getSettlementId());
    if (!c) return false;

    const PlayerId oldOwner = static_cast<PlayerId>(c->getOwnerId());
    if (oldOwner == newOwner) return false;

    // transfer owner
    c->setOwnerId(static_cast<uint8_t>(newOwner));

    // update player city lists (zakładam że masz)
    getPlayer(oldOwner).removeCity(c->getCityId());
    getPlayer(newOwner).addCity(c->getCityId());

    // Move the capturing unit's city assignment to the captured city.
    {
        const UnitId uOn = map.unitOn(pos);
        if (uOn != Map::kNoUnit) {
            reassignUnitToCity(cities, uOn, c->getCityId());
        }
    }

    // tile ownership marker / visuals
    // tile.setTribe(getPlayer(newOwner).getTribeType());

    // keep settlement id stable
    tile.setSettlement(SettlementTypeEnum::City, tile.getSettlementId());

    // Ensure territory is at least initialized around the city center.
    claimFreeTerritoryRadius1(map, c->getCityId(), tile.getSettlementId(), pos);

    return true;
}

bool Game::canUpgradeRaftToScout(UnitId unitId) const {
    return UnitUpgradeSystem::canUpgradeRaftToScout(*this, unitId);
}

bool Game::canUpgradeRaftToRammer(UnitId unitId) const {
    return UnitUpgradeSystem::canUpgradeRaftToRammer(*this, unitId);
}

bool Game::canUpgradeRaftToBomber(UnitId unitId) const {
    return UnitUpgradeSystem::canUpgradeRaftToBomber(*this, unitId);
}

bool Game::upgradeRaftToScout(UnitId unitId) {
    Unit* u = getUnit(unitId);
    if (!u) return false;
    if (!isPlayersTurn(u->getOwnerId())) return false;
    return UnitUpgradeSystem::upgradeRaftToScout(*this, unitId);
}

bool Game::upgradeRaftToRammer(UnitId unitId) {
    Unit* u = getUnit(unitId);
    if (!u) return false;
    if (!isPlayersTurn(u->getOwnerId())) return false;
    return UnitUpgradeSystem::upgradeRaftToRammer(*this, unitId);
}

bool Game::upgradeRaftToBomber(UnitId unitId) {
    Unit* u = getUnit(unitId);
    if (!u) return false;
    if (!isPlayersTurn(u->getOwnerId())) return false;
    return UnitUpgradeSystem::upgradeRaftToBomber(*this, unitId);
}

bool Game::canUnitBecomeVeteran(UnitId unitId) const {
    return UnitUpgradeSystem::canUnitBecomeVeteran(*this, unitId);
}

bool Game::becomeVeteran(UnitId unitId) {
    Unit* u = getUnit(unitId);
    if (!u) return false;
    if (!isPlayersTurn(u->getOwnerId())) return false;
    return UnitUpgradeSystem::becomeVeteran(*this, unitId);
}



