//
// Created by Fryderyk Niedzwiecki on 14/01/2026.
//

#include "Game.h"
#include "tribes/Tribe.h"
#include "tech/TechDB.h"

#include "Systems/TurnSystem.h"
#include "Systems/MovementSystem.h"
#include "Systems/CombatSystem.h"
#include "Systems/InteractionSystem.h"
#include "Systems/VisionSystem.h"
#include "Systems/BuildingSystem.h"
#include "Systems/TechSystem.h"
#include "Systems/PlayerSystem.h"
#include "Systems/UnitSpawnSystem.h"
#include "Systems/TileActionSystem.h"
#include <random>

#include "Systems/ScoreSystem.h"
#include "Systems/UnitSystem.h"
#include "Systems/CitySystem.h"

#include "Systems/UnitUpgradeSystem.h"
#include "Systems/CityUpgradeSystem.h"

#include <algorithm>
#include <iostream>

#include "World/Tile.h"
#include "terrain/SettlementId.h"

namespace {
    // SplitMix32-style mixing for deterministic pseudo-randomness.
    static inline uint32_t mix32(uint32_t x) {
        x += 0x9e3779b9u;
        x = (x ^ (x >> 16)) * 0x85ebca6bu;
        x = (x ^ (x >> 13)) * 0xc2b2ae35u;
        x ^= (x >> 16);
        return x;
    }

    static inline uint32_t seededPosRng(uint32_t worldSeed, Pos pos, uint32_t salt) {
        const uint32_t x = static_cast<uint32_t>(pos.x);
        const uint32_t y = static_cast<uint32_t>(pos.y);
        uint32_t h = worldSeed;
        h ^= mix32(x * 0x27d4eb2du);
        h ^= mix32(y * 0x165667b1u);
        h ^= mix32(salt);
        return mix32(h);
    }

    static inline int clampInt(int v, int lo, int hi) {
        return (v < lo) ? lo : (v > hi) ? hi : v;
    }
}

// Game.cpp
City* Game::getCity(CityId id) {
    if (id == kNoCity || id >= cities.size()) return nullptr;
    return &cities[id];
}

const City* Game::getCity(CityId id) const {
    if (id == kNoCity || id >= cities.size()) return nullptr;
    return &cities[id];
}

void Game::newGame(const NewGameConfig& cfg) {
    // 1) aktywne plemiona na mapie
    map.setActiveTribes(cfg.tribes);

    // 2) generacja mapy
    // Single source of truth for determinism.
    if (cfg.seed == 0) {
        std::random_device rd;
        worldSeed = (static_cast<uint32_t>(rd()) << 16) ^ static_cast<uint32_t>(rd());
        if (worldSeed == 0) worldSeed = 1u;
    } else {
        worldSeed = cfg.seed;
    }

    MapGenerator::Params p;
    p.mapSize = cfg.mapSize;
    p.initialLand = cfg.initialLand;
    p.smoothing = cfg.smoothing;
    p.relief = cfg.relief;
    p.seed = worldSeed;

    MapGenerator::generate(map, p);

    // Capitals generated by MapGenerator (same order as cfg.tribes / player indices)
    const auto& capitals = MapGenerator::getLastCapitals();

    cities.clear();
    cities.resize(cfg.tribes.size());

    for (size_t i = 0; i < cfg.tribes.size(); ++i) {
        const CityId cid = static_cast<CityId>(i);

        // Default city setup for all tribes
        (void)CitySystem::setCityId(*this, cid, cid);
        (void)CitySystem::setCityOwner(*this, cid, static_cast<uint8_t>(i));
        (void)CitySystem::setCityLevel(*this, cid, 1);
        (void)CitySystem::setCityPopulation(*this, cid, 0);
        (void)CitySystem::setCityStarsPerRound(*this, cid, 20);
        (void)CitySystem::setCityName(*this, cid, std::string("City ") + std::to_string(i));

        // IMPORTANT: store the city position (used by movement/connection systems).
        if (capitals.size() == cfg.tribes.size()) {
            (void)CitySystem::setCityPos(*this, cid, capitals[i]);
        }

        // Capitals generated by MapGenerator: each starting city is a capital
        (void)CitySystem::setCityCapital(*this, cid, true);

        // Special tribe rule: Luxidoor starts with a strong capital
        if (cfg.tribes[i] == TribeType::Luxidoor) {
            (void)CitySystem::setCityLevel(*this, cid, 3);
            (void)CitySystem::setCityStarsPerRound(*this, cid, 4);
            (void)CitySystem::setCityPopulation(*this, cid, 0);
        }
    }

    // 3) tworzymy graczy
    players.clear();
    players.reserve(cfg.tribes.size());

    for (size_t i = 0; i < cfg.tribes.size(); ++i) {
        PlayerId pid = static_cast<PlayerId>(i);

        // Startowe gwiazdki bierzemy z definicji plemienia (wiki defaults)
        const Tribe tribe = Tribe::makeDefault(cfg.tribes[i]);
        const int startStars = static_cast<int>(tribe.getStartStars());

        // capitalId is stable and matches MapGenerator (we use player index as capital/city id)
        const int capitalId = static_cast<int>(i);
        players.emplace_back(pid, cfg.tribes[i], startStars, capitalId);

        // Grant starting technology (new TechId-based tech system)
        const TechId startTech = tribe.getStartTech();
        if (startTech != TechId::Count) {
            PlayerSystem::addTech(*this, pid, startTech);
        }
    }

    // 3b) Initialize capitals (tile settlement + territory) via CitySystem.
    // Must happen after players are created, because initCapital also ensures player city list + capital id.
    if (capitals.size() == cfg.tribes.size()) {
        for (size_t i = 0; i < cfg.tribes.size(); ++i) {
            (void)CitySystem::initCapital(*this, static_cast<PlayerId>(i), static_cast<CityId>(i), capitals[i]);
        }
    }

    // 4) jednostki startowe
    units.clear();

    // 4b) spawn starting units on capitals (tribe default start unit)
    if (capitals.size() == cfg.tribes.size()) {
        for (size_t i = 0; i < players.size(); ++i) {
            const Pos cap = capitals[i];
            if (!map.inBounds(cap) || map.unitOn(cap) != Map::kNoUnit) continue;

            const Tribe tribe = Tribe::makeDefault(cfg.tribes[i]);
            const UnitType startType = tribe.getStartUnit().getType();

            const UnitId uid = spawnUnit(startType, static_cast<PlayerId>(i), cap, true);
            if (uid != kNoUnit) {
                (void)CitySystem::addUnitToCity(*this, uid, static_cast<CityId>(i));
            }
        }
    }

    // 4c) initial fog-of-war
    if (capitals.size() == players.size()) {
        for (size_t i = 0; i < players.size(); ++i) {
            VisionSystem::revealArea(*this, static_cast<PlayerId>(i), capitals[i], 2, RevealSource::Initial);
        }
    }

    for (size_t i = 0; i < players.size(); ++i) {
        VisionSystem::revealForPlayerFromUnits(*this, static_cast<PlayerId>(i));
    }

    currentPlayer = 0;
    turnNumber = 0;

    // 5) start tury gracza 0
    TurnSystem::startTurn(*this);
}

bool Game::buyTech(PlayerId pid, TechId tech) {
    if (!isPlayersTurn(pid)) return false;
    return TechSystem::buyTech(*this, pid, tech);
}

bool Game::endTurn(PlayerId pid) {
    if (!isPlayersTurn(pid)) return false;

    TurnSystem::endTurn(*this);

    currentPlayer = static_cast<PlayerId>((currentPlayer + 1) % players.size());
    if (currentPlayer == 0) {
        turnNumber++;
    }

    TurnSystem::startTurn(*this);
    return true;
}

Unit* Game::getUnit(UnitId id) {
    if (id == kNoUnit) return nullptr;
    if (id >= units.size()) return nullptr;
    return &units[id];
}

const Unit* Game::getUnit(UnitId id) const {
    if (id == kNoUnit) return nullptr;
    if (id >= units.size()) return nullptr;
    return &units[id];
}

// Spawns a unit on the map. If `canActImmediately` is false, the unit cannot move/attack until next turn.
UnitId Game::spawnUnit(UnitType type, PlayerId owner, Pos pos, bool canActImmediately) {
    if (!canActImmediately) {
        if (!isPlayersTurn(owner)) return kNoUnit;
        if (owner == kNoPlayer) return kNoUnit;
        if (!PlayerSystem::playerExists(*this, owner)) return kNoUnit;
    }

    return UnitSpawnSystem::spawnUnit(*this, map, type, owner, pos, canActImmediately);
}

bool Game::moveUnit(PlayerId pid, UnitId unitId, Pos to) {
    if (!UnitSystem::unitExists(*this, unitId)) return false;

    const PlayerId owner = UnitSystem::getOwnerId(*this, unitId);
    if (pid != owner) return false;
    if (!isPlayersTurn(pid)) return false;

    return MovementSystem::move(*this, unitId, to);
}

bool Game::handleRuin(PlayerId pid, UnitId unitId, Pos pos) {
    if (!UnitSystem::unitExists(*this, unitId)) return false;

    const PlayerId owner = UnitSystem::getOwnerId(*this, unitId);
    if (pid != owner) return false;
    if (!isPlayersTurn(pid)) return false;

    if (!map.inBounds(pos)) return false;

    InteractionSystem::handleRuin(*this, unitId, pos);
    return true;
}

int Game::getPlayerScore(PlayerId pid) const {
    return ScoreSystem::getScore(*this, pid);
}

bool Game::handleStarfish(PlayerId pid, UnitId unitId, Pos pos) {
    if (!UnitSystem::unitExists(*this, unitId)) return false;

    const PlayerId owner = UnitSystem::getOwnerId(*this, unitId);
    if (pid != owner) return false;
    if (!isPlayersTurn(pid)) return false;

    if (!map.inBounds(pos)) return false;

    InteractionSystem::handleStarfish(*this, unitId, pos);
    return true;
}

std::vector<Pos> Game::reachable(PlayerId pid, UnitId unitId) const {
    if (!UnitSystem::unitExists(*this, unitId)) return {};

    const PlayerId owner = UnitSystem::getOwnerId(*this, unitId);
    if (pid != owner) return {};
    if (!isPlayersTurn(pid)) return {};

    return MovementSystem::reachable(*this, unitId);
}

bool Game::attack(PlayerId pid, UnitId attackerId, Pos target) {
    if (!UnitSystem::unitExists(*this, attackerId)) return false;

    if (pid != UnitSystem::getOwnerId(*this, attackerId)) return false;
    if (!isPlayersTurn(pid)) return false;

    return CombatSystem::attack(*this, attackerId, target);
}


bool Game::heal(PlayerId pid, UnitId healerId) {
    if (!UnitSystem::unitExists(*this, healerId)) return false;

    const PlayerId owner = UnitSystem::getOwnerId(*this, healerId);
    if (pid != owner) return false;
    if (!isPlayersTurn(pid)) return false;

    return CombatSystem::heal(*this, healerId);
}

std::vector<Pos> Game::attackable(PlayerId pid, UnitId attackerId) const {
    if (!UnitSystem::unitExists(*this, attackerId)) return {};

    const PlayerId owner = UnitSystem::getOwnerId(*this, attackerId);
    if (pid != owner) return {};
    if (!isPlayersTurn(pid)) return {};

    return CombatSystem::attackable(*this, attackerId);
}

bool Game::buildBuilding(PlayerId builder, Pos pos, BuildingTypeEnum type) {
    if (!isPlayersTurn(builder)) return false;
    if (!map.inBounds(pos)) return false;

    const Tile& t = map.at(pos);
    const CityId cid = t.getTerritoryCityId();
    if (cid == kNoCity) return false;
    if (!CitySystem::cityExists(*this, cid)) return false;
    if (static_cast<PlayerId>(CitySystem::getCityOwner(*this, cid)) != builder) return false;

    return BuildingSystem::build(*this, builder, pos, type);
}

// ---- Tile actions wrappers ----

bool Game::hunt(PlayerId pid, Pos pos) {
    if (!isPlayersTurn(pid)) return false;
    if (!map.inBounds(pos)) return false;
    return TileActionSystem::hunt(*this, pid, pos);
}

bool Game::organization(PlayerId pid, Pos pos) {
    if (!isPlayersTurn(pid)) return false;
    if (!map.inBounds(pos)) return false;
    return TileActionSystem::organization(*this, pid, pos);
}

bool Game::fishing(PlayerId pid, Pos pos) {
    if (!isPlayersTurn(pid)) return false;
    if (!map.inBounds(pos)) return false;
    return TileActionSystem::fishing(*this, pid, pos);
}

bool Game::clearForest(PlayerId pid, Pos pos) {
    if (!isPlayersTurn(pid)) return false;
    if (!map.inBounds(pos)) return false;
    return TileActionSystem::clearForest(*this, pid, pos);
}

bool Game::burnForest(PlayerId pid, Pos pos) {
    if (!isPlayersTurn(pid)) return false;
    if (!map.inBounds(pos)) return false;
    return TileActionSystem::burnForest(*this, pid, pos);
}

bool Game::growForest(PlayerId pid, Pos pos) {
    if (!isPlayersTurn(pid)) return false;
    if (!map.inBounds(pos)) return false;
    return TileActionSystem::growForest(*this, pid, pos);
}

bool Game::destroyTile(PlayerId pid, Pos pos) {
    if (!isPlayersTurn(pid)) return false;
    if (!map.inBounds(pos)) return false;
    return TileActionSystem::destroy(*this, pid, pos);
}

bool Game::buildRoad(PlayerId pid, Pos pos) {
    if (!isPlayersTurn(pid)) return false;
    if (!map.inBounds(pos)) return false;
    return TileActionSystem::buildRoad(*this, pid, pos);
}

std::vector<BuildingTypeEnum> Game::getPlayerEarnedMonuments(PlayerId pid) const {
    if (!PlayerSystem::playerExists(*this, pid)) return {};
    return PlayerSystem::getEarnedMonuments(*this, pid);
}

std::vector<BuildingTypeEnum> Game::getPlayerPlacedMonuments(PlayerId pid) const {
    if (!PlayerSystem::playerExists(*this, pid)) return {};
    return PlayerSystem::getPlacedMonuments(*this, pid);
}

std::vector<BuildingTypeEnum> Game::getPlayerOwnedMonuments(PlayerId pid) const {
    if (!PlayerSystem::playerExists(*this, pid)) return {};
    return PlayerSystem::getOwnedMonuments(*this, pid);
}

bool Game::explorer(PlayerId pid, Pos start) {
    std::cout << "[explorer] pid=" << int(pid) << " start=(" << start.x << "," << start.y << ")\n";
    if (!isPlayersTurn(pid)) return false;
    if (!map.inBounds(start)) return false;
    VisionSystem::doExplorer(*this, pid, start);
    return true;
}

bool Game::buildBridge(PlayerId pid, Pos pos) {
    if (!isPlayersTurn(pid)) return false;
    if (!map.inBounds(pos)) return false;
    return TileActionSystem::buildBridge(*this, pid, pos);
}

// ---- City actions ----

bool Game::foundCityFromVillage(PlayerId pid, Pos pos) {
    if (!isPlayersTurn(pid)) return false;
    return CitySystem::foundCityFromVillage(*this, pid, pos);
}

bool Game::canUpgradeCity(PlayerId pid, CityId cityId) const {
    if (!isPlayersTurn(pid)) return false;
    if (!CitySystem::cityExists(*this, cityId)) return false;

    const PlayerId owner = static_cast<PlayerId>(CitySystem::getCityOwner(*this, cityId));
    if (owner != pid) return false;

    return CityUpgradeSystem::canUpgrade(*this, cityId);
}

CityUpgradeOptions Game::getCityUpgradeOptions(PlayerId pid, CityId cityId) const {
    CityUpgradeOptions out{};

    if (!isPlayersTurn(pid)) return out;
    if (!CitySystem::cityExists(*this, cityId)) return out;

    const PlayerId owner = static_cast<PlayerId>(CitySystem::getCityOwner(*this, cityId));
    if (owner != pid) return out;

    return CityUpgradeSystem::getUpgradeOptions(*this, cityId);
}

bool Game::upgradeCity(PlayerId pid, CityId cityId, CityUpgradeChoice choice) {
    if (!isPlayersTurn(pid)) return false;
    if (!CitySystem::cityExists(*this, cityId)) return false;

    const PlayerId owner = static_cast<PlayerId>(CitySystem::getCityOwner(*this, cityId));
    if (owner != pid) return false;

    return CityUpgradeSystem::tryUpgrade(*this, cityId, choice);
}


bool Game::captureCityAt(PlayerId pid, Pos pos) {
    if (!isPlayersTurn(pid)) return false;
    return CitySystem::captureCityAt(*this, pid, pos);
}

// ---- Raft upgrades (pid-first + legacy delegate) ----

bool Game::canUpgradeRaftToScout(PlayerId pid, UnitId unitId) const {
    if (!UnitSystem::unitExists(*this, unitId)) return false;

    const PlayerId owner = UnitSystem::getOwnerId(*this, unitId);
    if (pid != owner) return false;
    if (!isPlayersTurn(pid)) return false;

    return UnitUpgradeSystem::canUpgradeRaftToScout(*this, unitId);
}


bool Game::canUpgradeRaftToRammer(PlayerId pid, UnitId unitId) const {
    if (!UnitSystem::unitExists(*this, unitId)) return false;

    const PlayerId owner = UnitSystem::getOwnerId(*this, unitId);
    if (pid != owner) return false;
    if (!isPlayersTurn(pid)) return false;

    return UnitUpgradeSystem::canUpgradeRaftToRammer(*this, unitId);
}


bool Game::canUpgradeRaftToBomber(PlayerId pid, UnitId unitId) const {
    if (!UnitSystem::unitExists(*this, unitId)) return false;

    const PlayerId owner = UnitSystem::getOwnerId(*this, unitId);
    if (pid != owner) return false;
    if (!isPlayersTurn(pid)) return false;

    return UnitUpgradeSystem::canUpgradeRaftToBomber(*this, unitId);
}


bool Game::upgradeRaftToScout(PlayerId pid, UnitId unitId) {
    if (!UnitSystem::unitExists(*this, unitId)) return false;

    const PlayerId owner = UnitSystem::getOwnerId(*this, unitId);
    if (pid != owner) return false;
    if (!isPlayersTurn(pid)) return false;

    return UnitUpgradeSystem::upgradeRaftToScout(*this, unitId);
}


bool Game::upgradeRaftToRammer(PlayerId pid, UnitId unitId) {
    if (!UnitSystem::unitExists(*this, unitId)) return false;

    const PlayerId owner = UnitSystem::getOwnerId(*this, unitId);
    if (pid != owner) return false;
    if (!isPlayersTurn(pid)) return false;

    return UnitUpgradeSystem::upgradeRaftToRammer(*this, unitId);
}


bool Game::upgradeRaftToBomber(PlayerId pid, UnitId unitId) {
    if (!UnitSystem::unitExists(*this, unitId)) return false;

    const PlayerId owner = UnitSystem::getOwnerId(*this, unitId);
    if (pid != owner) return false;
    if (!isPlayersTurn(pid)) return false;

    return UnitUpgradeSystem::upgradeRaftToBomber(*this, unitId);
}


// ---- Veteran (pid-first + legacy delegate) ----

bool Game::canUnitBecomeVeteran(PlayerId pid, UnitId unitId) const {
    if (!UnitSystem::unitExists(*this, unitId)) return false;

    const PlayerId owner = UnitSystem::getOwnerId(*this, unitId);
    if (pid != owner) return false;
    if (!isPlayersTurn(pid)) return false;

    return UnitUpgradeSystem::canUnitBecomeVeteran(*this, unitId);
}


bool Game::becomeVeteran(PlayerId pid, UnitId unitId) {
    if (!UnitSystem::unitExists(*this, unitId)) return false;

    const PlayerId owner = UnitSystem::getOwnerId(*this, unitId);
    if (pid != owner) return false;
    if (!isPlayersTurn(pid)) return false;

    return UnitUpgradeSystem::becomeVeteran(*this, unitId);
}


uint16_t Game::getLighthouseDiscoveredByMask(uint8_t lighthouseIdx) const {
    return (lighthouseIdx < lighthouseDiscoveredBy.size()) ? lighthouseDiscoveredBy[lighthouseIdx] : 0;
}

bool Game::hasPlayerDiscoveredLighthouse(uint8_t lighthouseIdx, PlayerId pid) const {
    if (lighthouseIdx >= lighthouseDiscoveredBy.size()) return false;
    if (pid == kNoPlayer) return false;
    const uint16_t bit = static_cast<uint16_t>(1u << static_cast<uint16_t>(pid));
    return (lighthouseDiscoveredBy[lighthouseIdx] & bit) != 0;
}

bool Game::markLighthouseDiscovered(uint8_t lighthouseIdx, PlayerId pid) {
    if (lighthouseIdx >= lighthouseDiscoveredBy.size()) return false;
    if (pid == kNoPlayer) return false;

    const uint16_t bit = static_cast<uint16_t>(1u << static_cast<uint16_t>(pid));
    uint16_t& mask = lighthouseDiscoveredBy[lighthouseIdx];

    if (mask & bit) return false; // już odkrył wcześniej
    mask |= bit;
    return true;
}